version: '3.7'

services:
  server:
    build: .
    ports:
      - '3000:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env.development.local
    # command: sh -c "npm install && npm run start:watch"
    command: sh -c "npm install && npm run dev"
    networks:
      - server_network
    logging:
      driver: 'json-file'
      options:
        max-size: '10m' # Set the maximum log file size to 10 megabytes
        max-file: '3' # Set the maximum number of log files
        compress: 'true' # Enable log file compression

    # depends_on:
    #   - mongodb

  # mongodb:
  #   image: 'mongo:latest'
  #   volumes:
  #     - ./mongodb_data:/data/db
  #   ports:
  #     - '27017:27017'
  #   networks:
  #     - server_network

networks:
  server_network:
